var data = [
    {
        "hourlyWage": 450.0,
        "price": 450,
        "itemName": "检修、调校柴油高压油泵"
    }, {
        "hourlyWage": 60.0,
        "price": 60,
        "itemName": "清洗曲轴箱机油集滤器"
    }, {
        "hourlyWage": 450.0,
        "price": 450,
        "itemName": "换连杆轴承"
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "检查高速连杆轴承间隙"
    }, {
        "itemName": "检修空气压缩机"
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "换正时齿轮前油封"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "检修分电器"
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "换发动机前支承垫螺栓"
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "换发动机后支承垫螺栓"
    }, {
        "hourlyWage": 450.0,
        "price": 450,
        "itemName": "检修调试高压油泵"
    }, {
        "hourlyWage": 800.0,
        "price": 800,
        "itemName": "换发动机活塞、连杆"
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "发动机一级维护"
    }, {
        "hourlyWage": 400.0,
        "price": 400,
        "itemName": "发动机二级维护"
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "发动机芯速排污检验"
    }, {
        "hourlyWage": 50.0,
        "price": 50,
        "itemName": "换机油感应器、检修油压力"
    }, {
        "hourlyWage": 400.0,
        "price": 400,
        "itemName": "换柴油机气缸垫"
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "保养灯光系统"
    }, {
        "hourlyWage": 20.0,
        "price": 20,
        "itemName": "镶气门座    (个)"
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "检修燃油蒸发控制装置"
    }, {
        "hourlyWage": 400.0,
        "price": 400,
        "itemName": "检修正时链或齿"
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "换化油器"
    }, {
        "hourlyWage": 400.0,
        "price": 400,
        "itemName": "清洗分油器"
    }, {
        "hourlyWage": 800.0,
        "price": 800,
        "itemName": "分解、修理差速器"
    }, {
        "hourlyWage": 1000.0,
        "price": 1000,
        "itemName": "分解、修理手动变速器"
    }, {
        "hourlyWage": 160.0,
        "price": 160,
        "itemName": "更换或润滑波箱换档拉索"
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "保养方向系统"
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "换传动轴中间轴承或油封"
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "换油箱支架胶"
    }, {
        "hourlyWage": 1500.0,
        "price": 1500,
        "itemName": "后桥大修"
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "调校离合踏板"
    }, {
        "hourlyWage": 600.0,
        "price": 600,
        "itemName": "检修变速器跳档异响"
    }, {
        "hourlyWage": 600.0,
        "price": 600,
        "itemName": "检修变速器、减速器异响"
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "检修变速箱操纵机构"
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "初驶车辆保养"
    }, {
        "hourlyWage": 500.0,
        "price": 500,
        "itemName": "差速器大修"
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "检修减速器角齿油封"
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "检修后轮壳油封漏油"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换波箱档位显示器"
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "检修自动变速箱漏油"
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "时滞液压试验"
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "电器系统二级维"
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "更换变速杆"
    }, {
        "hourlyWage": 400.0,
        "price": 400,
        "itemName": "前独立悬挂解体、修理（单边）"
    }, {
        "hourlyWage": 400.0,
        "price": 400,
        "itemName": "后独立悬挂解体、修理（单边）"
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "更换后悬挂推杆"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换后悬挂稳定杆"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换螺旋弹簧（支）"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换前轮定位拉杆"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换后轮上挂臂"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换后轮下挂臂"
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "更换发动机后横梁"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换后悬挂（支）"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "换托盘前机"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "换托盘后机"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "检修前轮钢板弹簧断 (单边)"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "检修后轮钢板弹簧断 (单边)"
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "检修铆前钢板支架座 (单边)"
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "检修铆后板板支架座 (单边)"
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "调校前桥扭杆弹簧"
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "换独立悬挂弹簧"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "换前轴"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换钢板销及衬套     (单边)"
    }, {
        "hourlyWage": 240.0,
        "price": 240,
        "itemName": "检查调校前轮定位"
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "换前驱动轴"
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "换前或后钢板弹簧     (单边)"
    }, {
        "hourlyWage": 40.0,
        "price": 40,
        "itemName": "调整转向角度"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "检修横直拉杆"
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "换扭杆式前叉板胶套及轴"
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "检修可变悬挂系统"
    }, {
        "hourlyWage": 350.0,
        "price": 350,
        "itemName": "检修电子悬挂电路"
    }, {
        "hourlyWage": 600.0,
        "price": 600,
        "itemName": "检修自动悬挂装置"
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "更换后制动鼓"
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换后制动盘（个）"
    }, {
        "hourlyWage": 50.0,
        "price": 50,
        "itemName": "镗制动鼓（个）"
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "检修保养制动总泵"
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "更换制动总泵"
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "检修保养制动分泵（碟/边）"
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "检修保养制动分泵（鼓/边）"
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换制动分泵  (碟/边)"
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换制动分泵  (鼓/边)"
    }, {
        "hourlyWage": 700.0,
        "price": 700,
        "itemName": "保养电子燃油喷射系统"
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换车轮制动软管（条）"
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "调速手拉杆"
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "检验制动台检"
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "更换制动链"
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "换换刹车比例阀"
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "检修轮毂油封漏油(个）"
    }, {
        "hourlyWage": 350.0,
        "price": 350,
        "itemName": "检修四轮刹车(含换刹车皮\\分泵）"
    }, {
        "hourlyWage": 600.0,
        "price": 600,
        "itemName": "制动系统大修"
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "换储气筒"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "检修真空增压器"
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "调校刹车间隙"
    }, {
        "hourlyWage": 140.0,
        "price": 140,
        "itemName": "刹车鼓拆装磨光（个）"
    }, {
        "hourlyWage": 50.0,
        "price": 50,
        "itemName": "调校制动踏板行程"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换前桥(不含吊装发动机)"
    }, {
        "hourlyWage": 600.0,
        "price": 600,
        "itemName": "更换后桥"
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "检修转向拉杆机构"
    }, {
        "hourlyWage": 160.0,
        "price": 160,
        "itemName": "调整转向角度"
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "调整方向盘间隙"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "拆换转向节"
    }, {
        "hourlyWage": 350.0,
        "price": 350,
        "itemName": "换前轴（工字梁）"
    }, {
        "hourlyWage": 800.0,
        "price": 800,
        "itemName": "发动机小修"
    }, {
        "hourlyWage": 400.0,
        "price": 400,
        "itemName": "动力转向机大修"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "换动力液压泵修理包"
    }, {
        "hourlyWage": 400.0,
        "price": 400,
        "itemName": "检修转向机电控系统"
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "更换方向机主臂"
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "更换方向机付臂"
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "检修方向侧滑"
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "拆装前稳定杆（左右）"
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "拆装后稳定杆（左右）"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "换转向机十字轴"
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "换方向杆"
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "更换风量调节开关"
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "更换冷暖调节开关或拉索"
    }, {
        "hourlyWage": 60.0,
        "price": 60,
        "itemName": "更换储液罐"
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "检修冷气提速开关"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "检修排漏"
    }, {
        "hourlyWage": 500.0,
        "price": 500,
        "itemName": "清洗冷气风口、管道"
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "冷气风机检修"
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "拆装更换冷气温度感应器"
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "更换冷气温度显示器"
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "更换空调保险阀"
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "检修空调电路（自动）"
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "检修转速表线路"
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "检修机油压力线路（机油灯亮）"
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "检修充电指示灯线路"
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "更换电动天线总成或天线蕊"
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换普通天线"
    }, {
        "hourlyWage": 350.0,
        "price": 350,
        "itemName": "更换左右气袋及电脑"
    }, {
        "hourlyWage": 40.0,
        "price": 40,
        "itemName": "检修、更换前射灯"
    }, {
        "hourlyWage": 2000.0,
        "price": 2000,
        "itemName": "全车线路大修"
    }, {
        "hourlyWage": 20.0,
        "price": 20,
        "itemName": "取断头螺丝/支"
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "检修\\更换发电机"
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "换雨刮马达(不含拆装表台)"
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "检修电子防盗器系统"
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "放大电路故障"
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "排除供油系统电器故障"
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "回门控制故障"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "检修车速电器"
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "检修分电器"
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "检修电动窗电路"
    }, {
        "hourlyWage": 20.0,
        "price": 20,
        "itemName": "拆装更换门灯感应器"
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "检修安全带感应器"
    }, {
        "hourlyWage": 60.0,
        "price": 60,
        "itemName": "更换手刹灯感应器"
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "拆检尾门锁灯开关总成"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "检修充电灯常着"
    }, {
        "hourlyWage": 600.0,
        "price": 600,
        "itemName": "检修全车灯光信号"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "检修灯光开关总成"
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "拆装或更换谐振箱"
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "检修电动天线"
    }, {
        "hourlyWage": 450.0,
        "price": 450,
        "itemName": "检修电子燃油喷射系统"
    }, {
        "hourlyWage": 20.0,
        "price": 20,
        "itemName": "更换电池线（负）"
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "检修自动波外控电器"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "检修液压方向机电子控制系统"
    }, {
        "hourlyWage": 350.0,
        "price": 350,
        "itemName": "检修自动防撞系统（仪表台）"
    }, {
        "hourlyWage": 400.0,
        "price": 400,
        "itemName": "检修四轮驱动电控器"
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "配装收放机"
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "检修大灯高低调整装置"
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "检查发电量"
    }, {
        "hourlyWage": 60.0,
        "price": 60,
        "itemName": "更换水道闷头"
    }, {
        "hourlyWage": 600.0,
        "price": 600,
        "itemName": "拆装仪表台总成"
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "更换发动机仓前龙门架"
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "更换发动机盖锁并调整"
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "更换电动倒车镜(个)"
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "更换前翼子板"
    }, {
        "hourlyWage": 450.0,
        "price": 450,
        "itemName": "更换后翼子板"
    }, {
        "hourlyWage": 160.0,
        "price": 160,
        "itemName": "更换前门玻璃（件）"
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "拆装后门饰板（件）"
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "拆装向管柱"
    }, {
        "hourlyWage": 350.0,
        "price": 350,
        "itemName": "更换车身前立柱"
    }, {
        "hourlyWage": 400.0,
        "price": 400,
        "itemName": "更换车身中立柱"
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换落水槽饰条（条）"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换前门升降器或马达"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换后门升降器或马达"
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "更换门锁驱动器（个）"
    }, {
        "hourlyWage": 160.0,
        "price": 160,
        "itemName": "更换行李箱盖"
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "更换全车标志"
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "更换后门三角窗"
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "更换油箱拉索"
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "拆装行李箱内饰件"
    }, {
        "hourlyWage": 60.0,
        "price": 60,
        "itemName": "更换行李箱后围板"
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换行李箱拉簧"
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换谐振箱"
    }, {
        "hourlyWage": 60.0,
        "price": 60,
        "itemName": "更换后轮内挡泥衬胶（单边）"
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "更换后保险杠上支架"
    }, {
        "hourlyWage": 60.0,
        "price": 60,
        "itemName": "更换门柱外饰铰"
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "更换后盖铰"
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换前或后门门铰（个）"
    }, {
        "hourlyWage": 60.0,
        "price": 60,
        "itemName": "更换室内倒车镜"
    }, {
        "hourlyWage": 40.0,
        "price": 40,
        "itemName": "更换前转向灯"
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "修玻璃升降器手动"
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "焊补排气管"
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "检修排气箱"
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "调校门"
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "检修中门轴承"
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "检修前盖或后门撑"
    }, {
        "hourlyWage": 30.0,
        "price": 30,
        "itemName": "更换前转向灯"
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "油箱修补"
    }, {
        "hourlyWage": 50.0,
        "price": 50,
        "itemName": "调校车门"
    }, {
        "hourlyWage": 50.0,
        "price": 50,
        "itemName": "调校门锁位"
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "调校玻璃升降器"
    }, {
        "hourlyWage": 650.0,
        "price": 650,
        "itemName": "发动机盖烤漆旧件"
    }, {
        "hourlyWage": 700.0,
        "price": 700,
        "itemName": "发动机盖烤漆残破"
    }, {
        "hourlyWage": 600.0,
        "price": 600,
        "itemName": "前保险杠烤漆残破"
    }, {
        "hourlyWage": 500.0,
        "price": 500,
        "itemName": "前保险杠补漆新件"
    }, {
        "hourlyWage": 500.0,
        "price": 500,
        "itemName": "前叶子板烤漆新件"
    }, {
        "hourlyWage": 450.0,
        "price": 450,
        "itemName": "后叶子板烤漆新件"
    }, {
        "hourlyWage": 550.0,
        "price": 550,
        "itemName": "后叶子板烤漆残破"
    }, {
        "hourlyWage": 500.0,
        "price": 500,
        "itemName": "前车门烤漆新件"
    }, {
        "hourlyWage": 550.0,
        "price": 550,
        "itemName": "前车门烤漆旧件"
    }, {
        "hourlyWage": 600.0,
        "price": 600,
        "itemName": "前车门烤漆残破"
    }, {
        "hourlyWage": 500.0,
        "price": 500,
        "itemName": "后车门烤漆新件"
    }, {
        "hourlyWage": 550.0,
        "price": 550,
        "itemName": "后车门烤漆旧件"
    }, {
        "hourlyWage": 600.0,
        "price": 600,
        "itemName": "后车门烤漆残破"
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "前立柱烤漆旧件"
    }, {
        "hourlyWage": 350.0,
        "price": 350,
        "itemName": "前立柱烤漆残破"
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "拆装或更换空滤器总成"
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "中立柱烤漆旧件"
    }, {
        "hourlyWage": 350.0,
        "price": 350,
        "itemName": "中立柱烤漆残破"
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "后立柱烤漆旧件"
    }, {
        "hourlyWage": 350.0,
        "price": 350,
        "itemName": "后立柱烤漆残破"
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "车门上幅烤漆旧件"
    }, {
        "hourlyWage": 350.0,
        "price": 350,
        "itemName": "车门上幅烤漆残破"
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "车门下幅烤漆旧件"
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "车门下幅烤漆残破"
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "车门防撞条烤漆/"
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "车身下裙条烤漆新件"
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "车身下裙条烤漆旧件"
    }, {
        "hourlyWage": 350.0,
        "price": 350,
        "itemName": "车身下裙条烤漆残破"
    }, {
        "hourlyWage": 550.0,
        "price": 550,
        "itemName": "行李箱盖烤漆旧件"
    }, {
        "hourlyWage": 600.0,
        "price": 600,
        "itemName": "行李箱盖烤漆残破"
    }, {
        "hourlyWage": 650.0,
        "price": 650,
        "itemName": "车顶烤漆旧件"
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "倒车镜烤漆新件"
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "倒车镜烤漆旧件"
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "大梁修复后烤漆"
    }, {
        "hourlyWage": 800.0,
        "price": 800,
        "itemName": "全车内外沙板凹位霉烂位修复及校正轻微"
    }, {
        "hourlyWage": 1200.0,
        "price": 1200,
        "itemName": "全车内外沙板凹位霉烂位修复及校正一般"
    }, {
        "hourlyWage": 2500.0,
        "price": 2500,
        "itemName": "全车内外沙板凹位霉烂位修复及校正严重"
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "发动机盖凹位修复 及较正一般"
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "发动机盖凹位修复 及较正严重"
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "右后叶子板凹位修复及校正严重"
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "车顶凹位修复及校正一般"
    }, {
        "hourlyWage": 400.0,
        "price": 400,
        "itemName": "车顶凹位修复及校正严重"
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "左前立柱凹位修复及校正轻微"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "左前立柱凹位修复及校正一般"
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "左前立柱凹位修复及校正严重"
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "右前立柱凹位修复及校正轻微"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "右前立柱凹位修复及校正一般"
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "右前立柱凹位修复及校正严重"
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "左中柱凹位修复及校正轻微"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "左中柱凹位修复及校正一般"
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "左中柱凹位修复及校正严重"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "右中柱凹位修复及校正一般"
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "右中柱凹位修复及校正严重"
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "右后门凹位修复及校正严重"
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "右后叶子板凹位修复及校正轻微"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "右后叶子板凹位修复及校正一般"
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "右后叶子板凹位修复及校正严重"
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "行李箱盖凹位修复及校正轻微"
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "行李箱盖凹位修复及校正一般"
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "行李箱盖凹位修复及校正严重"
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "前保险杠凹位修复及校正一般"
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "后保险杠凹位修复及校正轻微"
    }, {
        "hourlyWage": 350.0,
        "price": 350,
        "itemName": "后保险杠凹位修复及校正严重"
    }, {
        "hourlyWage": 600.0,
        "price": 600,
        "itemName": "修复前大梁(后)轻微"
    }, {
        "hourlyWage": 800.0,
        "price": 800,
        "itemName": "修复前大梁(后)一般"
    }, {
        "hourlyWage": 2000.0,
        "price": 2000,
        "itemName": "修复前大梁(后)严重"
    }, {
        "hourlyWage": 700.0,
        "price": 700,
        "itemName": "修复前、后大梁轻微"
    }, {
        "hourlyWage": 2000.0,
        "price": 2000,
        "itemName": "修复前、后大梁一般"
    }, {
        "hourlyWage": 3000.0,
        "price": 3000,
        "itemName": "修复前、后大梁严重"
    }, {
        "hourlyWage": 160.0,
        "price": 160,
        "itemName": "中门沙板修复一般"
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "中门沙板修复严重"
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "轮胎上盖板修复轻微"
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "轮胎上盖板修复一般"
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "轮胎上盖板修复严重"
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "车尾后幅修复 轻微"
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "车尾后幅修复 一般"
    }, {
        "hourlyWage": 500.0,
        "price": 500,
        "itemName": "车尾后幅修复 严重"
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "车头前幅修复轻微"
    }, {
        "hourlyWage": 500.0,
        "price": 500,
        "itemName": "车头前幅修复严重"
    }, {
        "hourlyWage": 1800.0,
        "price": 1800,
        "itemName": "车身大修一般"
    }, {
        "hourlyWage": 2500.0,
        "price": 2500,
        "itemName": "车身大修严重"
    }, {
        "hourlyWage": 280.0,
        "price": 280,
        "itemName": "前档风玻璃框锈蚀修复一般"
    }, {
        "hourlyWage": 350.0,
        "price": 350,
        "itemName": "前档风玻璃框锈蚀修复严重"
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "后档玻璃框锈蚀修复轻微"
    }, {
        "hourlyWage": 280.0,
        "price": 280,
        "itemName": "后档玻璃框锈蚀修复一般"
    }, {
        "hourlyWage": 350.0,
        "price": 350,
        "itemName": "后档玻璃框锈蚀修复严重"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "车顶沙板修复轻微"
    }, {
        "hourlyWage": 400.0,
        "price": 400,
        "itemName": "车顶沙板修复严重"
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "修复车身部份沙板（每幅）轻微"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "修复车身部份沙板（每幅）严重"
    }, {
        "hourlyWage": 160.0,
        "price": 160,
        "itemName": "修复前或后地板轻微"
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "修复前或后地板一般"
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "修复龙门架一般"
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "修复龙门架严重"
    }, {
        "hourlyWage": 1200.0,
        "price": 1200,
        "itemName": "更换右前大梁"
    }, {
        "hourlyWage": 1200.0,
        "price": 1200,
        "itemName": "更换左前大梁"
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "检修起动机"
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "保养发电机"
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "补充排气管吊胶"
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "清洗燃油箱",
        "useNum": 1
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "检修离合器液压分泵",
        "useNum": 1
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "150000公里全车保养",
        "useNum": 1
    }, {
        "hourlyWage": 400.0,
        "price": 400,
        "itemName": "换汽油机气缸垫",
        "useNum": 1
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "检修曲轴通风装置",
        "useNum": 1
    }, {
        "hourlyWage": 350.0,
        "price": 350,
        "itemName": "铲发动机积碳",
        "useNum": 1
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "加装电子点火",
        "useNum": 1
    }, {
        "hourlyWage": 2500.0,
        "price": 2500,
        "itemName": "分解、修理自动变速器",
        "useNum": 1
    }, {
        "hourlyWage": 160.0,
        "price": 160,
        "itemName": "更换或润滑波箱油门拉索",
        "useNum": 1
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "换传动轴万向节总成/个",
        "useNum": 1
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "电器系统一级维",
        "useNum": 1
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "检修P档锁止开关",
        "useNum": 1
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "拆装或更换转向节",
        "useNum": 1
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "拆装、更换后减震上座",
        "useNum": 1
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "检修空压式悬架避震系统",
        "useNum": 1
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "拆装羊角或转向销  (单边)",
        "useNum": 1
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "更换前或后制动片（一付）",
        "useNum": 1
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换前制动盘（个）",
        "useNum": 1
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换制动底板",
        "useNum": 1
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "发动机、底盘一保",
        "useNum": 1
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "调整手制动",
        "useNum": 1
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "拆装转向管柱",
        "useNum": 1
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "拆装转向横拉杆",
        "useNum": 1
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "换方向机中尺",
        "useNum": 1
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "保养方向机",
        "useNum": 1
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "更换方向机油散热器",
        "useNum": 1
    }, {
        "hourlyWage": 500.0,
        "price": 500,
        "itemName": "前桥转向系统大修",
        "useNum": 1
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "调整前轴转向节",
        "useNum": 1
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "检修压缩机磁吸",
        "useNum": 1
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "换制冷管（条）",
        "useNum": 1
    }, {
        "hourlyWage": 400.0,
        "price": 400,
        "itemName": "发动机、底盘二保",
        "useNum": 1
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "拆装修复冷凝网",
        "useNum": 1
    }, {
        "hourlyWage": 350.0,
        "price": 350,
        "itemName": "检修自动空调控制系统",
        "useNum": 1
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "检修水温表线路",
        "useNum": 1
    }, {
        "hourlyWage": 20.0,
        "price": 20,
        "itemName": "调整大灯位置及光轴",
        "useNum": 1
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "检查、调整气门间隙",
        "useNum": 1
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "更换后音响喇叭（个）",
        "useNum": 1
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换气袋线盘",
        "useNum": 1
    }, {
        "hourlyWage": 40.0,
        "price": 40,
        "itemName": "更换前保险杠灯（只）",
        "useNum": 1
    }, {
        "hourlyWage": 160.0,
        "price": 160,
        "itemName": "检修手刹灯线路",
        "useNum": 1
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "检修挂档杆灯线路",
        "useNum": 1
    }, {
        "hourlyWage": 450.0,
        "price": 450,
        "itemName": "拆修电动天窗机构",
        "useNum": 1
    }, {
        "hourlyWage": 8010.0,
        "price": 8010,
        "itemName": "检修原厂防盗系统",
        "useNum": 1
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "换保险盒",
        "useNum": 1
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "检修巡航控制系统电路",
        "useNum": 1
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "拆装燃油箱",
        "useNum": 1
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "换仪表灯台灯泡",
        "useNum": 1
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "车身保养",
        "useNum": 1
    }, {
        "hourlyWage": 350.0,
        "price": 350,
        "itemName": "检修加速防滑系统",
        "useNum": 1
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "检修电子仪表电路",
        "useNum": 1
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换发电机调节器（IC）",
        "useNum": 1
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "检修喷水电路",
        "useNum": 1
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "安装车尾静电线",
        "useNum": 1
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "更换组合仪表总成（拆装）",
        "useNum": 1
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "发动机电脑控测",
        "useNum": 1
    }, {
        "hourlyWage": 1000.0,
        "price": 1000,
        "itemName": "拆装车身饰件",
        "useNum": 1
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "更换后门玻璃绒槽",
        "useNum": 1
    }, {
        "hourlyWage": 350.0,
        "price": 350,
        "itemName": "拆装电动天窗机构",
        "useNum": 1
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "更换车身下裙(边)",
        "useNum": 1
    }, {
        "hourlyWage": 50.0,
        "price": 50,
        "itemName": "更换门玻璃内压条",
        "useNum": 1
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "更换前保险杠上支架",
        "useNum": 1
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "换单门锁芯",
        "useNum": 1
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "换引擎盖锁",
        "useNum": 1
    }, {
        "hourlyWage": 160.0,
        "price": 160,
        "itemName": "检修车头盖锁",
        "useNum": 1
    }, {
        "hourlyWage": 40.0,
        "price": 40,
        "itemName": "固定保险杠角胶",
        "useNum": 1
    }, {
        "hourlyWage": 550.0,
        "price": 550,
        "itemName": "前保险杠烤漆旧件",
        "useNum": 1
    }, {
        "hourlyWage": 600.0,
        "price": 600,
        "itemName": "前叶子板烤漆残破",
        "useNum": 1
    }, {
        "hourlyWage": 500.0,
        "price": 500,
        "itemName": "后叶子板烤漆旧件",
        "useNum": 1
    }, {
        "hourlyWage": 500.0,
        "price": 500,
        "itemName": "行李箱盖烤漆新件",
        "useNum": 1
    }, {
        "hourlyWage": 700.0,
        "price": 700,
        "itemName": "车顶烤漆残破",
        "useNum": 1
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "发动机内沙板喷漆",
        "useNum": 1
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "车顶凹位修复及校正轻微",
        "useNum": 1
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "左前门凹位修复及校正严重",
        "useNum": 1
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "右前门凹位修复及校正严重",
        "useNum": 1
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "左下裙条凹位修复及校正严重",
        "useNum": 1
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "右中柱凹位修复及校正轻微",
        "useNum": 1
    }, {
        "hourlyWage": 350.0,
        "price": 350,
        "itemName": "前保险杠凹位修复及校正严重",
        "useNum": 1
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "中门沙板修复轻微",
        "useNum": 1
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "车头前幅修复一般",
        "useNum": 1
    }, {
        "hourlyWage": 1000.0,
        "price": 1000,
        "itemName": "车身大修轻微",
        "useNum": 1
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "前档风玻璃框锈蚀修复轻微",
        "useNum": 1
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "车顶沙板修复一般",
        "useNum": 1
    }, {
        "hourlyWage": 400.0,
        "price": 400,
        "itemName": "修复前或后地板严重",
        "useNum": 1
    }, {
        "hourlyWage": 1000.0,
        "price": 1000,
        "itemName": "吊装车厢",
        "useNum": 1
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "调整点火正时",
        "useNum": 1
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "拆装处理排气管前端接口漏气",
        "useNum": 1
    }, {
        "hourlyWage": 550.0,
        "price": 550,
        "itemName": "检修气门漏气",
        "useNum": 2
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换检查电喷、水温感应器",
        "useNum": 2
    }, {
        "hourlyWage": 350.0,
        "price": 350,
        "itemName": "检修正时皮带异响或漏油",
        "useNum": 2
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "保养传动轴",
        "useNum": 2
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "检查变速箱齿轮油",
        "useNum": 2
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "更换制动片（碟刹一付)",
        "useNum": 2
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "换助力泵油壶",
        "useNum": 2
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "拆装后平行杆",
        "useNum": 2
    }, {
        "hourlyWage": 800.0,
        "price": 800,
        "itemName": "空调系统全面检修",
        "useNum": 2
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "改装压缩泵支架",
        "useNum": 2
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "检修里程表线路",
        "useNum": 2
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "拆装音响主机",
        "useNum": 2
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换前大灯或大灯座（只）",
        "useNum": 2
    }, {
        "hourlyWage": 40.0,
        "price": 40,
        "itemName": "更换前角灯（只）",
        "useNum": 2
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "检修电动后视镜及电路",
        "useNum": 2
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "检修、清除气囊故障",
        "useNum": 2
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "拆装雨刮及机构",
        "useNum": 2
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换门防水胶条（条）",
        "useNum": 2
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "解除ABS故障",
        "useNum": 2
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "检修电动座椅电路",
        "useNum": 2
    }, {
        "hourlyWage": 60.0,
        "price": 60,
        "itemName": "检修行车灯、尾灯",
        "useNum": 2
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "检修小灯电路",
        "useNum": 2
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换发电机整流器",
        "useNum": 2
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "检修倒车灯电路",
        "useNum": 2
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换里程表",
        "useNum": 2
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "更换发动机盖拉索拉手",
        "useNum": 2
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "拆装驾驶室天花",
        "useNum": 2
    }, {
        "hourlyWage": 50.0,
        "price": 50,
        "itemName": "电池架烧焊固定",
        "useNum": 2
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "更换车身电镀饰板",
        "useNum": 2
    }, {
        "hourlyWage": 30.0,
        "price": 30,
        "itemName": "换叶子板饰条",
        "useNum": 2
    }, {
        "hourlyWage": 5500.0,
        "price": 5500,
        "itemName": "全车烤漆内外",
        "useNum": 2
    }, {
        "hourlyWage": 600.0,
        "price": 600,
        "itemName": "发动机盖烤漆新件",
        "useNum": 2
    }, {
        "hourlyWage": 500.0,
        "price": 500,
        "itemName": "前保险杠烤漆新件",
        "useNum": 2
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "发动机盖凹位修复 及较正轻微",
        "useNum": 2
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "左前叶子板凹位修复及校正轻微",
        "useNum": 2
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "皮带张紧力调节",
        "useNum": 2
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "右下裙条凹位修复及校正严重",
        "useNum": 2
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "修复车身部份沙板（每幅）一般",
        "useNum": 2
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "修复龙门架轻微",
        "useNum": 2
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "40000公里定期保养",
        "useNum": 2
    }, {
        "hourlyWage": 1200.0,
        "price": 1200,
        "itemName": "换发动机全套活塞环",
        "useNum": 3
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "清洁怠速控制器",
        "useNum": 3
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "换水淹子  (不含拆装附件）",
        "useNum": 3
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换前驱动半轴（边）",
        "useNum": 3
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "换差速器油封",
        "useNum": 3
    }, {
        "hourlyWage": 1200.0,
        "price": 1200,
        "itemName": "检修波箱液压油路板",
        "useNum": 3
    }, {
        "hourlyWage": 450.0,
        "price": 450,
        "itemName": "检修离合器总成",
        "useNum": 3
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "更换发动机前横梁",
        "useNum": 3
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换前悬挂（支）",
        "useNum": 3
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "换悬挂上或下球头（只）",
        "useNum": 3
    }, {
        "hourlyWage": 60.0,
        "price": 60,
        "itemName": "调校前轮前束",
        "useNum": 3
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "保养或更换手刹拉线",
        "useNum": 3
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换制动踏板",
        "useNum": 3
    }, {
        "hourlyWage": 380.0,
        "price": 380,
        "itemName": "免拆氢氧机除发动机内积碳",
        "useNum": 3
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "前速检测、调整",
        "useNum": 3
    }, {
        "hourlyWage": 600.0,
        "price": 600,
        "itemName": "大修方向机",
        "useNum": 3
    }, {
        "hourlyWage": 60.0,
        "price": 60,
        "itemName": "调正方向盘位置",
        "useNum": 3
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "换助力泵高压或低压油管",
        "useNum": 3
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "拆装前平行杆",
        "useNum": 3
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "换方向锁",
        "useNum": 3
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "换方向减震器",
        "useNum": 3
    }, {
        "hourlyWage": 60.0,
        "price": 60,
        "itemName": "更换A/C开关",
        "useNum": 3
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "更换暖风水箱(不含拆表台)",
        "useNum": 3
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "修补、拆装换蒸发器",
        "useNum": 3
    }, {
        "hourlyWage": 1200.0,
        "price": 1200,
        "itemName": "空调系统大修",
        "useNum": 3
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "检修雨刮喷水机构(不含拆装仪表台总成)",
        "useNum": 3
    }, {
        "hourlyWage": 600.0,
        "price": 600,
        "itemName": "检修发动机燃油喷射系统",
        "useNum": 3
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "更换仪表板照明灯泡",
        "useNum": 3
    }, {
        "hourlyWage": 50.0,
        "price": 50,
        "itemName": "更换刹车油量感应器",
        "useNum": 3
    }, {
        "hourlyWage": 40.0,
        "price": 40,
        "itemName": "更换电池线及接头",
        "useNum": 3
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "更换前门锁机并调整（个）",
        "useNum": 3
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "更换后门锁机并调整",
        "useNum": 3
    }, {
        "hourlyWage": 160.0,
        "price": 160,
        "itemName": "更换门玻璃（件）",
        "useNum": 3
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "安装全车电镀眉",
        "useNum": 3
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "更换水箱上支架",
        "useNum": 3
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换车门内拉手  (只)不含拆装门饰板",
        "useNum": 3
    }, {
        "hourlyWage": 60.0,
        "price": 60,
        "itemName": "拆装前排座椅(张)",
        "useNum": 3
    }, {
        "hourlyWage": 60.0,
        "price": 60,
        "itemName": "更换前轮内挡泥衬胶（单边）",
        "useNum": 3
    }, {
        "hourlyWage": 60.0,
        "price": 60,
        "itemName": "更换车门防撞胶",
        "useNum": 3
    }, {
        "hourlyWage": 1000.0,
        "price": 1000,
        "itemName": "拆装全车附件",
        "useNum": 3
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "修复备胎架",
        "useNum": 3
    }, {
        "hourlyWage": 600.0,
        "price": 600,
        "itemName": "前保险杠补漆残破",
        "useNum": 3
    }, {
        "hourlyWage": 550.0,
        "price": 550,
        "itemName": "前叶子板烤漆旧件",
        "useNum": 3
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "左下裙条凹位修复及校正轻微",
        "useNum": 3
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "左后叶子板凹位修复及校正严重",
        "useNum": 3
    }, {
        "hourlyWage": 600.0,
        "price": 600,
        "itemName": "更换发动机缸盖",
        "useNum": 3
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "保养冷却系统",
        "useNum": 4
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换变速箱前油封",
        "useNum": 4
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "更换米表线",
        "useNum": 4
    }, {
        "hourlyWage": 500.0,
        "price": 500,
        "itemName": "尾牙大修",
        "useNum": 4
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "更换真空助力器",
        "useNum": 4
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "检修发动机油路（化油器）",
        "useNum": 4
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "检修暖气系统",
        "useNum": 4
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "检修燃油表线路",
        "useNum": 4
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换后门升降器或马达",
        "useNum": 4
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "检修雨刮喷水电路",
        "useNum": 4
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "检修门窗电路",
        "useNum": 4
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换车门（个）",
        "useNum": 4
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "更换冷却风扇马达",
        "useNum": 4
    }, {
        "hourlyWage": 40.0,
        "price": 40,
        "itemName": "更换油箱开启盖",
        "useNum": 4
    }, {
        "hourlyWage": 60.0,
        "price": 60,
        "itemName": "更换车门防水胶条  (边)",
        "useNum": 4
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换大灯下支架",
        "useNum": 4
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "换全车身彩条",
        "useNum": 4
    }, {
        "hourlyWage": 50.0,
        "price": 50,
        "itemName": "调校尾门",
        "useNum": 4
    }, {
        "hourlyWage": 600.0,
        "price": 600,
        "itemName": "车顶烤漆新件",
        "useNum": 4
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "左前叶子板凹位修复及校正严重",
        "useNum": 4
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "前保险杠凹位修复及校正轻微",
        "useNum": 4
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "检查、更换分火线、分火头及分火盖",
        "useNum": 4
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "拆装或更换分电器",
        "useNum": 4
    }, {
        "hourlyWage": 450.0,
        "price": 450,
        "itemName": "更换水泵及防冻液(如拆正时皮带)",
        "useNum": 5
    }, {
        "hourlyWage": 380.0,
        "price": 380,
        "itemName": "免拆清洗引擎油路    (缸/个)",
        "useNum": 5
    }, {
        "hourlyWage": 350.0,
        "price": 350,
        "itemName": "更换正时齿轮",
        "useNum": 5
    }, {
        "hourlyWage": 50.0,
        "price": 50,
        "itemName": "清洗更换燃油滤清器",
        "useNum": 5
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "检修挂挡机构",
        "useNum": 5
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "检修更换波箱电磁阀",
        "useNum": 5
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换前上挂臂",
        "useNum": 5
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "更换后轮油封",
        "useNum": 5
    }, {
        "hourlyWage": 160.0,
        "price": 160,
        "itemName": "检查及调较四轮刹车（含放空气）",
        "useNum": 5
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "更换空调泵电磁离合器",
        "useNum": 5
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "更换发动机左侧支承胶",
        "useNum": 5
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换暖水开关阀",
        "useNum": 5
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "检修调节器",
        "useNum": 5
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "检修发电机异响",
        "useNum": 5
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "检修SRS装置",
        "useNum": 5
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "保养发电机",
        "useNum": 5
    }, {
        "hourlyWage": 50.0,
        "price": 50,
        "itemName": "更换旁通水管",
        "useNum": 5
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "拆装前门内饰板（件）",
        "useNum": 5
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "更换水箱下支架",
        "useNum": 5
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换车门限位器   (个)",
        "useNum": 5
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换前叶子板内托（左或右）",
        "useNum": 5
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "左后门凹位修复及校正一般",
        "useNum": 5
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "左后门凹位修复及校正严重",
        "useNum": 5
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "后保险杠凹位修复及校正一般",
        "useNum": 5
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "检修发电机及线路",
        "useNum": 5
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "一级维护",
        "useNum": 6
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "检修汽油泵",
        "useNum": 6
    }, {
        "hourlyWage": 550.0,
        "price": 550,
        "itemName": "更换波箱壳",
        "useNum": 6
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换半轴内球笼（边）",
        "useNum": 6
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "检修传动轴",
        "useNum": 6
    }, {
        "hourlyWage": 450.0,
        "price": 450,
        "itemName": "底盘中修",
        "useNum": 6
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "检修助力泵",
        "useNum": 6
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "清洗、拆装干燥瓶",
        "useNum": 6
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "更换前门音响喇叭（个）",
        "useNum": 6
    }, {
        "hourlyWage": 40.0,
        "price": 40,
        "itemName": "更换前转向灯",
        "useNum": 6
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "检修刹车灯常着",
        "useNum": 6
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "发动机保养归零",
        "useNum": 6
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "更换前门玻璃绒槽（条）",
        "useNum": 6
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "换尾箱盖锁",
        "useNum": 6
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "更换后盖拉线",
        "useNum": 6
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "拆装、更换排气管第二段",
        "useNum": 6
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "60000公里定期保养",
        "useNum": 6
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "80000里定期保养",
        "useNum": 7
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "更换轮毂轴承(个)",
        "useNum": 7
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换变速箱后油封",
        "useNum": 7
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "拆装、更换前减震上座",
        "useNum": 7
    }, {
        "hourlyWage": 50.0,
        "price": 50,
        "itemName": "拆装空调进气滤网",
        "useNum": 7
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换空调管路",
        "useNum": 7
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "检修空调部分异响",
        "useNum": 7
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "拆修雨刮连杆机构(不含拆装表台总成)",
        "useNum": 7
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换前门升降器或马达",
        "useNum": 7
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换转向组合开关",
        "useNum": 7
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "更换汽油泵（机械泵）",
        "useNum": 7
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "检修仪表电路",
        "useNum": 7
    }, {
        "hourlyWage": 20.0,
        "price": 20,
        "itemName": "更换电池线（正）",
        "useNum": 7
    }, {
        "hourlyWage": 50.0,
        "price": 50,
        "itemName": "更换前格栅",
        "useNum": 7
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "左下裙条凹位修复及校正一般",
        "useNum": 7
    }, {
        "hourlyWage": 60.0,
        "price": 60,
        "itemName": "更换连接水管（水泵至节温器）",
        "useNum": 7
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "100000公里定期保养",
        "useNum": 8
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "维修或保养离合器分泵",
        "useNum": 8
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换前轮避震器座胶",
        "useNum": 8
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "更换发动机后支承胶",
        "useNum": 8
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "排除空调漏水",
        "useNum": 8
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "更换调温控开关",
        "useNum": 8
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "检修中央门锁",
        "useNum": 8
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "拆装倒车雷达",
        "useNum": 8
    }, {
        "hourlyWage": 350.0,
        "price": 350,
        "itemName": "更换后叶子板内托（左或右）",
        "useNum": 8
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "左后叶子板凹位修复及校正一般",
        "useNum": 8
    }, {
        "hourlyWage": 350.0,
        "price": 350,
        "itemName": "检修全车灯光信号",
        "useNum": 9
    }, {
        "hourlyWage": 50.0,
        "price": 50,
        "itemName": "换助力泵油",
        "useNum": 9
    }, {
        "hourlyWage": 350.0,
        "price": 350,
        "itemName": "检修、拆装冷气泵",
        "useNum": 9
    }, {
        "hourlyWage": 1200.0,
        "price": 1200,
        "itemName": "更换车顶",
        "useNum": 9
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "调怠速",
        "useNum": 10
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "检修，拆装膨胀阀",
        "useNum": 10
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "更换冷气皮带调整轮",
        "useNum": 10
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "检修雨刮电路",
        "useNum": 10
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "更换汽油箱",
        "useNum": 10
    }, {
        "hourlyWage": 600.0,
        "price": 600,
        "itemName": "全车内填面喷漆（不含材料）",
        "useNum": 10
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "左前门凹位修复及校正轻微",
        "useNum": 10
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "左前门凹位修复及校正一般",
        "useNum": 10
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "左后门凹位修复及校正轻微",
        "useNum": 10
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "清洗空气滤清器或更换滤芯",
        "useNum": 11
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "保养空调系统",
        "useNum": 11
    }, {
        "hourlyWage": 60.0,
        "price": 60,
        "itemName": "换下摆臂缓冲胶",
        "useNum": 11
    }, {
        "hourlyWage": 2200.0,
        "price": 2200,
        "itemName": "底盘大修",
        "useNum": 11
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "更换方向机横拉杆",
        "useNum": 11
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换车门外拉手 (只)不含拆装门饰板",
        "useNum": 11
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "更换发动机支架",
        "useNum": 12
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换ABS执行器",
        "useNum": 12
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "拆装、更换刹车总泵修理包",
        "useNum": 12
    }, {
        "hourlyWage": 400.0,
        "price": 400,
        "itemName": "检修ABS系统",
        "useNum": 12
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "更换蒸发器(不含拆表台)",
        "useNum": 12
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "更换后高位制动灯灯泡",
        "useNum": 12
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换天窗开关",
        "useNum": 12
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换室内倒车镜",
        "useNum": 12
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换水泵及防冻液",
        "useNum": 12
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换发动机盖",
        "useNum": 12
    }, {
        "hourlyWage": 10.0,
        "price": 10,
        "itemName": "补充排气管吊胶",
        "useNum": 12
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "拆装、更换排气管前段",
        "useNum": 12
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "拆装、更换排气管第三段",
        "useNum": 12
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "右下裙条凹位修复及校正一般",
        "useNum": 12
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "调校手刹车",
        "useNum": 13
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "拆装空调鼓风机",
        "useNum": 13
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "检修电子扇电路",
        "useNum": 13
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "检修起动线路",
        "useNum": 13
    }, {
        "hourlyWage": 350.0,
        "price": 350,
        "itemName": "更换前或后挡风玻璃",
        "useNum": 13
    }, {
        "hourlyWage": 1500.0,
        "price": 1500,
        "itemName": "校正大梁",
        "useNum": 13
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "20000公里保养",
        "useNum": 13
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "右前门凹位修复及校正轻微",
        "useNum": 13
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "调前束",
        "useNum": 14
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "更换发动机右侧支承胶",
        "useNum": 14
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "更换雨刮喷水壶或喷水电机",
        "useNum": 14
    }, {
        "hourlyWage": 550.0,
        "price": 550,
        "itemName": "前保险杠补漆旧件",
        "useNum": 14
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "换传动轴十字头",
        "useNum": 15
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "后保险杠补漆局部",
        "useNum": 15
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "右后门凹位修复及校正轻微",
        "useNum": 15
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "更换风扇偶合器",
        "useNum": 15
    }, {
        "hourlyWage": 20.0,
        "price": 20,
        "itemName": "研磨气门    (个)",
        "useNum": 16
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换平衡杆小连杆",
        "useNum": 16
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "更换钢圈，平衡轮胎（四轮）",
        "useNum": 16
    }, {
        "hourlyWage": 40.0,
        "price": 40,
        "itemName": "更换喷油嘴 (支)",
        "useNum": 16
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "更换节气门阀体",
        "useNum": 16
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "检修起动机",
        "useNum": 16
    }, {
        "hourlyWage": 50.0,
        "price": 50,
        "itemName": "换机油感应器",
        "useNum": 17
    }, {
        "hourlyWage": 400.0,
        "price": 400,
        "itemName": "更换后桥",
        "useNum": 17
    }, {
        "hourlyWage": 350.0,
        "price": 350,
        "itemName": "检修方向机",
        "useNum": 17
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "检修CD收放机外接电路",
        "useNum": 17
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "检修大灯电路",
        "useNum": 17
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换挡泥胶（四轮）",
        "useNum": 17
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "右后叶子板凹位修复及校正轻微",
        "useNum": 17
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "右下裙条凹位修复及校正轻微",
        "useNum": 17
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "拆装排气管岐管",
        "useNum": 17
    }, {
        "hourlyWage": 50.0,
        "price": 50,
        "itemName": "换付水箱",
        "useNum": 18
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "拆装平衡杆",
        "useNum": 18
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "拆装或更换后轮轴承（边）",
        "useNum": 18
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "全车美容护理",
        "useNum": 18
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "清洗化油器",
        "useNum": 19
    }, {
        "hourlyWage": 50.0,
        "price": 50,
        "itemName": "更换门玻璃外压条",
        "useNum": 19
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "废气检测",
        "useNum": 19
    }, {
        "hourlyWage": 50.0,
        "price": 50,
        "itemName": "换气油格",
        "useNum": 19
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "维修或保养离合器总泵",
        "useNum": 20
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "更换前轮油封",
        "useNum": 21
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换仪表总成",
        "useNum": 21
    }, {
        "hourlyWage": 350.0,
        "price": 350,
        "itemName": "更换天窗玻璃",
        "useNum": 21
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "前或后幅喷漆",
        "useNum": 21
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "右前门凹位修复及校正一般",
        "useNum": 21
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "右后门凹位修复及校正一般",
        "useNum": 21
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "检修更换机油格座",
        "useNum": 22
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换半轴外球笼（边）",
        "useNum": 22
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "传动轴动平衡",
        "useNum": 22
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "清洗、拆装散热网",
        "useNum": 22
    }, {
        "hourlyWage": 450.0,
        "price": 450,
        "itemName": "拆装变速箱总成",
        "useNum": 23
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "拆装或更换前轮轴承（边）",
        "useNum": 24
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "更换手刹片",
        "useNum": 24
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "换雪种瓶",
        "useNum": 24
    }, {
        "hourlyWage": 650.0,
        "price": 650,
        "itemName": "拆装仪表台总成",
        "useNum": 24
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "更换方向机助力油泵",
        "useNum": 25
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "更换电子扇或电子扇马达",
        "useNum": 25
    }, {
        "hourlyWage": 40.0,
        "price": 40,
        "itemName": "更换差速器油",
        "useNum": 26
    }, {
        "hourlyWage": 400.0,
        "price": 400,
        "itemName": "更换前桥",
        "useNum": 26
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "检修喇叭电路",
        "useNum": 26
    }, {
        "hourlyWage": 160.0,
        "price": 160,
        "itemName": "底盘喷防锈漆（不含材料）",
        "useNum": 26
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "检修转向灯线路",
        "useNum": 27
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "换点火开关",
        "useNum": 27
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "左后叶子板凹位修复及校正轻微",
        "useNum": 27
    }, {
        "hourlyWage": 30.0,
        "price": 30,
        "itemName": "换火咀筒胶圈（个）",
        "useNum": 29
    }, {
        "hourlyWage": 600.0,
        "price": 600,
        "itemName": "吊装发动机总成",
        "useNum": 29
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "检修ABS电路",
        "useNum": 29
    }, {
        "hourlyWage": 60.0,
        "price": 60,
        "itemName": "更换横拉杆内球头（个）",
        "useNum": 30
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换半轴防尘套、保养球笼",
        "useNum": 31
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "更换机油泵总成",
        "useNum": 31
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "配装遥控器",
        "useNum": 32
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "修玻璃升降器电动",
        "useNum": 32
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "更换传动轴吊胶",
        "useNum": 34
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换方向盘",
        "useNum": 34
    }, {
        "hourlyWage": 50.0,
        "price": 50,
        "itemName": "更换空调继电器",
        "useNum": 34
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "龙门架喷漆",
        "useNum": 34
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "左前叶子板凹位修复及校正一般",
        "useNum": 34
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "换方向机球头",
        "useNum": 35
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "换空调高压管",
        "useNum": 37
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "更换安全带",
        "useNum": 37
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "拆装或更换水箱、更换防冻液",
        "useNum": 37
    }, {
        "hourlyWage": 60.0,
        "price": 60,
        "itemName": "更换横拉杆外球头（个）",
        "useNum": 38
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "右后叶子板凹位修复及校正一般",
        "useNum": 38
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换前下挂臂",
        "useNum": 39
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "电脑解除故障码",
        "useNum": 39
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换升降器总开关",
        "useNum": 40
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "焊补排气管",
        "useNum": 40
    }, {
        "hourlyWage": 50.0,
        "price": 50,
        "itemName": "更换尾门撑杆(支)",
        "useNum": 41
    }, {
        "hourlyWage": 50.0,
        "price": 50,
        "itemName": "更换发动机下挡板",
        "useNum": 42
    }, {
        "hourlyWage": 600.0,
        "price": 600,
        "itemName": "清洗及调整喷油嘴（全车套）节气门、进气岐管",
        "useNum": 42
    }, {
        "hourlyWage": 500.0,
        "price": 500,
        "itemName": "检修刹车系统",
        "useNum": 43
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "更换冷凝器",
        "useNum": 43
    }, {
        "hourlyWage": 50.0,
        "price": 50,
        "itemName": "更换前大灯（个）",
        "useNum": 43
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "更换油箱",
        "useNum": 46
    }, {
        "hourlyWage": 40.0,
        "price": 40,
        "itemName": "更换方向助力泵皮带",
        "useNum": 46
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "拆装波箱油底壳",
        "useNum": 48
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "更换油门拉线",
        "useNum": 48
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "更换节温器盖",
        "useNum": 49
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "换离合器分离轴承",
        "useNum": 50
    }, {
        "hourlyWage": 160.0,
        "price": 160,
        "itemName": "更换大灯组合开关",
        "useNum": 50
    }, {
        "hourlyWage": 350.0,
        "price": 350,
        "itemName": "检修全车灯光线路",
        "useNum": 51
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "更换波箱吊胶",
        "useNum": 52
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换汽油泵（电动泵）",
        "useNum": 53
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "测漏、加雪种（R12）",
        "useNum": 54
    }, {
        "hourlyWage": 450.0,
        "price": 450,
        "itemName": "更换正时皮带、调整配气正时",
        "useNum": 54
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "检修空调电路",
        "useNum": 57
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "换凸轮轴传感器",
        "useNum": 58
    }, {
        "hourlyWage": 40.0,
        "price": 40,
        "itemName": "更换变速箱齿轮油",
        "useNum": 63
    }, {
        "hourlyWage": 20.0,
        "price": 20,
        "itemName": "更换轮胎平衡动力",
        "useNum": 63
    }, {
        "hourlyWage": 1800.0,
        "price": 1800,
        "itemName": "发动机中修",
        "useNum": 63
    }, {
        "hourlyWage": 30.0,
        "price": 30,
        "itemName": "更换冷气泵皮带",
        "useNum": 64
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "清洗蒸发器",
        "useNum": 66
    }, {
        "hourlyWage": 30.0,
        "price": 30,
        "itemName": "更换电喇叭",
        "useNum": 66
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "更换曲轴皮带轮",
        "useNum": 66
    }, {
        "hourlyWage": 40.0,
        "price": 40,
        "itemName": "更换后尾灯（只）",
        "useNum": 69
    }, {
        "hourlyWage": 60.0,
        "price": 60,
        "itemName": "更换方向机防尘套",
        "useNum": 70
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "清洗水箱加冷却液",
        "useNum": 71
    }, {
        "hourlyWage": 50.0,
        "price": 50,
        "itemName": "更换机油感应器",
        "useNum": 73
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "更换起动机总成",
        "useNum": 77
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "前保险杠补漆局部",
        "useNum": 79
    }, {
        "hourlyWage": 60.0,
        "price": 60,
        "itemName": "更换平行杆球头(个)",
        "useNum": 80
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "更换机油、机油滤清器、空气滤清器",
        "useNum": 81
    }, {
        "hourlyWage": 450.0,
        "price": 450,
        "itemName": "更换气缸垫",
        "useNum": 81
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "更换ABS转速传感器（个）",
        "useNum": 82
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换后保险杠",
        "useNum": 83
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "更换转向灯灯泡（个）",
        "useNum": 85
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "电池充电",
        "useNum": 87
    }, {
        "hourlyWage": 30.0,
        "price": 30,
        "itemName": "更换雨刮臂",
        "useNum": 87
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "安装防盗器",
        "useNum": 87
    }, {
        "hourlyWage": 10.0,
        "price": 10,
        "itemName": "更换轮胎螺丝 (支)",
        "useNum": 92
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换前中网",
        "useNum": 93
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换前减震器（支）",
        "useNum": 96
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "检修发动机故障灯亮",
        "useNum": 100
    }, {
        "hourlyWage": 50.0,
        "price": 50,
        "itemName": "换继电器",
        "useNum": 105
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "拆装进气岐管",
        "useNum": 106
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换后减震器（支）",
        "useNum": 110
    }, {
        "hourlyWage": 50.0,
        "price": 50,
        "itemName": "更换下水管",
        "useNum": 112
    }, {
        "hourlyWage": 450.0,
        "price": 450,
        "itemName": "更换全车锁",
        "useNum": 114
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "装倒车雷达",
        "useNum": 120
    }, {
        "hourlyWage": 20.0,
        "price": 20,
        "itemName": "清洗喷油嘴    (支)",
        "useNum": 122
    }, {
        "hourlyWage": 500.0,
        "price": 500,
        "itemName": "更换曲轴后油封",
        "useNum": 122
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "更换平衡杆胶",
        "useNum": 129
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "电脑检测",
        "useNum": 133
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "拆装油底壳",
        "useNum": 147
    }, {
        "hourlyWage": 140.0,
        "price": 140,
        "itemName": "刹车碟拆装磨光（个）",
        "useNum": 148
    }, {
        "hourlyWage": 500.0,
        "price": 500,
        "itemName": "二级维护",
        "useNum": 160
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "新车1000公里、5000公里保养",
        "useNum": 163
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换空调散热网",
        "useNum": 169
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "更换皮带张紧轮",
        "useNum": 175
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "更换发电机总成",
        "useNum": 179
    }, {
        "hourlyWage": 3500.0,
        "price": 3500,
        "itemName": "发动机大修",
        "useNum": 191
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "拆装气门室盖",
        "useNum": 192
    }, {
        "hourlyWage": 400.0,
        "price": 400,
        "itemName": "检修发动机漏油",
        "useNum": 193
    }, {
        "hourlyWage": 550.0,
        "price": 550,
        "itemName": "更换离合器片",
        "useNum": 203
    }, {
        "hourlyWage": 50.0,
        "price": 50,
        "itemName": "更换上水管",
        "useNum": 206
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "部分沙板喷漆（每幅）",
        "useNum": 213
    }, {
        "hourlyWage": 450.0,
        "price": 450,
        "itemName": "更换方向机总成",
        "useNum": 214
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "检修底盘异响",
        "useNum": 215
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "更换助力泵",
        "useNum": 223
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "更换曲轴前油封",
        "useNum": 224
    }, {
        "hourlyWage": 40.0,
        "price": 40,
        "itemName": "更换空调皮带",
        "useNum": 231
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "更换前保险杠",
        "useNum": 245
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "换发电机",
        "useNum": 264
    }, {
        "hourlyWage": 100.0,
        "price": 100,
        "itemName": "更换半轴油封",
        "useNum": 284
    }, {
        "hourlyWage": 120.0,
        "price": 120,
        "itemName": "测漏、加雪种（R134a）",
        "useNum": 312
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "更换机油滤清器",
        "useNum": 324
    }, {
        "hourlyWage": 500.0,
        "price": 500,
        "itemName": "拆装仪表台",
        "useNum": 329
    }, {
        "hourlyWage": 600.0,
        "price": 600,
        "itemName": "油电路保养",
        "useNum": 332
    }, {
        "hourlyWage": 200.0,
        "price": 200,
        "itemName": "检修水温高",
        "useNum": 360
    }, {
        "hourlyWage": 10.0,
        "price": 10,
        "itemName": "轮胎平衡",
        "useNum": 419
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "清洗发动机(外表)",
        "useNum": 433
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "更换轮胎，平衡轮胎（四轮）",
        "useNum": 437
    }, {
        "hourlyWage": 300.0,
        "price": 300,
        "itemName": "更换压缩机",
        "useNum": 479
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "抽真空加雪种",
        "useNum": 490
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "更换大灯灯泡（个）",
        "useNum": 510
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "更换节温器",
        "useNum": 510
    }, {
        "hourlyWage": 20.0,
        "price": 20,
        "itemName": "平衡轮胎",
        "useNum": 716
    }, {
        "hourlyWage": 150.0,
        "price": 150,
        "itemName": "更换水泵",
        "useNum": 719
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "清洗节气门、怠速阀",
        "useNum": 767
    }, {
        "hourlyWage": 10.0,
        "price": 10,
        "itemName": "更换火花塞    (个)",
        "useNum": 933
    }, {
        "hourlyWage": 250.0,
        "price": 250,
        "itemName": "保养四轮刹车",
        "useNum": 1071
    }, {
        "hourlyWage": 180.0,
        "price": 180,
        "itemName": "更换水箱",
        "useNum": 1109
    }, {
        "hourlyWage": 50.0,
        "price": 50,
        "itemName": "更换方向机油",
        "useNum": 1165
    }, {
        "hourlyWage": 40.0,
        "price": 40,
        "itemName": "更换发电机皮带",
        "useNum": 1341
    }, {
        "hourlyWage": 20.0,
        "price": 20,
        "itemName": "更换防冻液",
        "useNum": 1400
    }, {
        "hourlyWage": 240.0,
        "price": 240,
        "itemName": "四轮定位检修、调整",
        "useNum": 1570
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "更换雨刮片",
        "useNum": 3374
    }, {
        "hourlyWage": 30.0,
        "price": 30,
        "itemName": "更换波箱油",
        "useNum": 3633
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "更换电池",
        "useNum": 4936
    }, {
        "hourlyWage": 80.0,
        "price": 80,
        "itemName": "更换刹车油",
        "useNum": 5364
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "更换机油",
        "useNum": 6374
    }, {
        "hourlyWage": 0.0,
        "price": 0,
        "itemName": "更换机油、机油格",
        "useNum": 14019
    }
];

module.exports = {
    data
}